### ISSUE TITLE
Generation Mod Implementation?

### ISSUE THREAD

**Issue by AbnormalMatrix** [gullyn/pymcworld#1]
Hello,
This project looks very promising. I feature suggestion I have is the ability to generate customized worlds from mods, like Terraforged. Is this realistic?
Thanks

**Comment by gullyn** [comment]
It isn't the best way to create custom terrain, because it doesn't create the world while the game is being played. If you want to create a 1000x1000 map, for instance, that's doable, but the library doesn't work that well at more than 100,000,000 blocks in a world.
